### ISSUE TITLE
Specific timeline for ROS2 version

### ISSUE THREAD

**Issue by Taeyoung96** [KOKIAOKI/3d_bbs#15]
Hi @KOKIAOKI!  

In #10, you mention that the ROS2 version for 3d_bbs will be updated.  

Is there a specific date for this update?

Thanks,

**Comment by KOKIAOKI** [comment]
Hi @Taeyoung96!  Thank you for your inquiry!

ROS2 and cpu version for 3d_bbs are almost complete on the branch, 
but I haven't merged it yet because of my graduation and conference presentation recently.

Thank you for waiting for the update.
I will merge the branch in this week or next week as possible.

After merge it, I have a favor to ask of you.
Could you implement the docker support for ros2 test as well?

**Comment by Taeyoung96** [comment]
@KOKIAOKI   
I also have a workload for graduation, but I'm going to try it! :smile:  
What is the ros2 version of docker you use, is it humble?

**Comment by KOKIAOKI** [comment]
I see! Let's do our best for graduation! 👍

> What is the ros2 version of docker you use, is it humble?  

Yes.

**Comment by KOKIAOKI** [comment]
v1.2.0 is scheduled to be released by January 28th.
I am rebuilding the design for better maintainability.

**Comment by KOKIAOKI** [comment]
@Taeyoung96 
Thank you very much for your patience. I have now released the ros2 version.

If you have the time, I would also appreciate Docker support for ros2_test.

Thank you again.

**Comment by Taeyoung96** [comment]
@KOKIAOKI   
Got it. I'll try with the docker.    
I have a question. Is it acceptable to experiment with a dockerfile that is separate from the one currently provided?  
Or should I leverage the dockerfile that is currently available?

**Comment by KOKIAOKI** [comment]
@Taeyoung96 
Thank you so much.
Either is fine! It’s up to you.

**Comment by Taeyoung96** [comment]
@KOKIAOKI   
I'll close this issue for now and reopen it if there are any issues, thank you. 😄
